CREATE TABLE IF NOT EXISTS `project` (
    `id` BIGINT PRIMARY KEY COMMENT '主键',
    `name` VARCHAR(200) UNIQUE NOT NULL DEFAULT '' COMMENT '项目名',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE IF NOT EXISTS `log` (
    `id` BIGINT PRIMARY KEY COMMENT '主键',
    `project_id` BIGINT NOT NULL DEFAULT 0 COMMENT '项目id',
    `log` MEDIUMTEXT COMMENT '日志内容',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE IF NOT EXISTS "config" (
    `id` BIGINT PRIMARY KEY COMMENT '主键',
    `project_id` BIGINT NOT NULL DEFAULT 0 COMMENT '项目id',
    `config` MEDIUMTEXT COMMENT '配置内容',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE IF NOT EXISTS "global_config" (
    `project_id` BIGINT PRIMARY KEY COMMENT '项目id',
    `config` MEDIUMTEXT COMMENT '配置内容',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);

